apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vz8axkx9b-java-springboot
  janus-idp.io/tekton: vz8axkx9b-java-springboot
  backstage.io/kubernetes-id: vz8axkx9b-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vz8axkx9b-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
